blank_issues_enabled: true
contact_links:
  - name: Extreme Launcher Matrix Support Room
    url: https://matrix.to/#/#extreme-support:matrix.org
    about: Please ask for support here before opening an issue.
