name: Publish to WinGet
on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: ExtremeLauncher.ExtremeLauncher
          version: ${{ github.event.release.tag_name }}
          installers-regex: 'ExtremeLauncher-Windows-MSVC(:?-arm64|-Legacy)?-Setup-.+\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
